apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jackett.fullname" . }}-config
  labels:
    {{- include "jackett.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
