apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "symfony-app.fullname" . }}
  labels:
    {{- include "symfony-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "symfony-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/nginx: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "symfony-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "symfony-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "symfony-app.fullname" . }}-nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          workingDir: /app
          ports:
            - name: http
              containerPort: {{ .Values.service.nginx.port }}
              protocol: TCP
          {{- toYaml .Values.probes.nginx | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-directory
              mountPath: /app
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
              readOnly: true
        - name: {{ include "symfony-app.fullname" . }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.fpm.repository }}:{{ .Values.image.fpm.tag }}"
          imagePullPolicy: {{ .Values.image.fpm.pullPolicy }}
          workingDir: /app
          ports:
            - name: fpm
              containerPort: {{ .Values.service.fpm.port }}
              protocol: TCP
          {{- toYaml .Values.probes.fpm | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-directory
              mountPath: /app
      initContainers:
        - name: init-fetch-code
          image: "{{ .Values.image.git.repository }}:{{ .Values.image.git.tag }}"
          workingDir: /app
          env:
            - name: GIT_SSH_COMMAND
              value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -vvvvv"
          volumeMounts:
            - name: app-directory
              mountPath: /app
          command: [ 'sh', '-c', "git clone --depth 1 --branch {{ .Values.appVersion }} {{ .Values.appSource }} /app" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        - name: dependencies-composer
          image: "{{ .Values.image.php.repository }}:{{ .Values.image.php.tag }}"
          workingDir: /app
          volumeMounts:
            - name: app-directory
              mountPath: /app
          command: [ 'sh', '-c', "composer install  --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader --optimize-autoloader" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ template "symfony-app.fullname" . }}-nginx-config
        - name: app-directory
          emptyDir: {}