apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "symfony-app.fullname" . }}-environment
  labels:
    {{- include "symfony-app.labels" . | nindent 4 }}
data:
  {{- tpl .Values.environment $ | nindent 2 }}