# Default values for mastodon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/mastodon/mastodon
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

mastodon:
  environment:
    secret_key_base:
    otp_secret: ''
    local_https: 'true'
    local_domain: 'example.social'
  # ~ are unconfigured values
  smtp:
    host: smtp.eu.mailgun.org
    port: 587
    username: postmaster@localhost
    password: xxxxxxxxxxxxxxxxxxx-yyyyyyyy-zzzzzzz
    from: noreply@localhost
    domain: ~
    deliveryMethod: smtp
    authMethod: plain
    verifyMode: peer
    startTlsAuto: ~
    startTls: auto # Set to auto (default), always, or never.
    tls: ~
    ssl: ~
  crons:
    - name: media-remove
      schedule: '* * * * *'
      command: [/home/mastodon/live/bin/tootctl, media, remove]
    - name: preview-card-remove
      schedule: '* * * * *'
      command: [/home/mastodon/live/bin/tootctl, preview_cards, remove]
jobs:
  createAdmin:
    enabled: false
    deleteOnSuccess: true
    username: instance_admin
    email: admin@localhost

postgresql:
  host: ''
  port: ~
  credentials:
    database: mastodon
    username: mastodon
    password: ''

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

sidekiq:
  workers:
    - name: default
      concurrency: 1
      queues:
        - default
    - name: push-pull
      concurrency: 2
      queues:
        - push
        - pull
    - name: mailers
      concurrency: 1
      queues:
        - mailers
    - name: scheduler
      concurrency: 1
      queues:
        - scheduler
    - name: ingress
      concurrency: 1
      queues:
        - ingress

# When connecting to a `postgres-operator` database, set sslMode to 'no-verify' and enable `rejectUnauthorized`
streaming:
  port: 4000
  replicas: 1
  workers: 1
  rejectUnauthorized: false
  db:
    sslMode: ~
    # sslMode: 'no-verify'

redis:
  enabled: true
  hostname: ""
  port: 6379
  existingSecret: ""

minio:
  api:
    # Set your mastodon host
    host: 'example.social'
    # Also to be configued in alias_host
    path: '/s3'
    rewriteIngress: true
  enabled: true

s3:
  enabled: true
  # When minio.api is enabled the keys
  # can be obtained from the Minio Console
  # available at http://mastodon-minio:9001
  access_key: "xxxxx"
  access_secret: "yyyyyyyyyyy"
  # When minio.api is enabled the bucket can
  # be configured at the Minio Console
  #  # available at http://mastodon-minio:9001
  bucket: "mastodon"
  endpoint: "http://mastodon-minio:9000"
  hostname: ~
  region: ~
  permission: ~
  protocol: 'https'
  # For the default settings with the s3 ingress,
  # update the `example.social` host to your hostname
  alias_host: 'example.social/s3/mastodon'