{{- $context := . }}
{{- range .Values.mastodon.crons }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mastodon.fullname" $context }}-{{ .name }}
spec:
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ include "mastodon.fullname" $context }}-media-remove
              image: "{{ $context.Values.image.repository }}:{{ $context.Values.image.tag | default $context.Chart.AppVersion }}"
              imagePullPolicy: IfNotPresent
              command: {{ .command }}
              envFrom:
                - configMapRef:
                    name: {{ include "mastodon.fullname" $context }}-environment
              env:
{{ include "mastodon.redis.environmentSecrets" $context | indent 16 }}
          restartPolicy: OnFailure
---
{{- end }}