apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mastodon.fullname" . }}-environment
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
data:
  {{- if .Values.mastodon.environment.otp_secret }}
  OTP_SECRET: {{ required "otp_secret must be set" (.Values.mastodon.environment.otp_secret | quote) }}
  {{- end }}
  {{- if not (empty .Values.mastodon.environment.secret_key_base) }}
  SECRET_KEY_BASE: {{ required "secret_key_base must be set" (.Values.mastodon.environment.secret_key_base | b64enc | quote) }}
  {{- end }}
  DB_HOST: {{ .Values.postgresql.host }}
  DB_PORT: {{ .Values.postgresql.port | default "5432" | quote }}
  DB_NAME: {{ .Values.postgresql.credentials.database }}
  DB_USER: {{ .Values.postgresql.credentials.username }}
  DB_PASS: {{ .Values.postgresql.credentials.password }}
  LOCAL_HTTPS: {{ .Values.mastodon.environment.local_https | quote }}
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{template "mastodon.redis.fullname" . }}-master
  {{- else }}
  REDIS_HOST: {{required "When the redis chart is disabled .Values.redis.hostname is required" .Values.redis.hostname }}
  {{- end }}
  REDIS_PORT: {{.Values.redis.port | default "6379" | quote }}