apiVersion: v2
name: jackett
description: API Support for your favorite torrent trackers

type: application
version: 1.2.0
appVersion: "0.24.82"
icon: https://avatars.githubusercontent.com/u/15383019?s=48&v=4
